adminUser:
  password: local:minikube/adminUser:password
  username: admin
docker:
  email: cmenedes@doitt.nyc.gov
  password: local:minikube/docker:password
  url: https://index.docker.io/v1/
  username: cmenedes
enableDocker: true
pipelineUser:
  email: cmenedes@yahoo.com
  token: local:minikube/pipelineUser:token
  username: cmenedes
prow:
  hmacToken: local:minikube/prow:hmacToken
